name: SurvivalGames
version: 1.0
main: com.mineswine.sg.SurvivalGames
description: Custom survival games!!!

commands:
     forcestart:
          description: Force start the game in lobby!
     forceend:
          description: Force end the game!
     stats:
          description: Check your stats on SG!